# Generated by Django 5.2.3 on 2025-06-27 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('Created', models.DateTimeField(default=datetime.datetime(2025, 6, 27, 15, 19, 24, 917647))),
            ],
        ),
    ]
