# Generated by Django 5.2.3 on 2025-06-27 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_testdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdate',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 16, 27, 46, 914238)),
        ),
    ]
