# Generated by Django 5.2.3 on 2025-06-27 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_testdate_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdate',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 17, 24, 20, 927318)),
        ),
    ]
